{% set version = "3.1.2" %}

package:
    name: uncertainties
    version: {{ version }}

source:
  url: https://pypi.io/packages/source/u/uncertainties/uncertainties-{{ version }}.tar.gz
  sha256: ba07c17a8a78cb58a47cd373079c7ea459f8b26cd474e29163b6ba0d72856a1e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy

test:
  imports:
    - uncertainties
    - uncertainties.unumpy
  requires:
    - numpy

about:
  home: https://pypi.python.org/pypi/uncertainties
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'Transparent calculations with uncertainties on the quantities involved (aka "error propagation"); fast calculation of derivatives.'

extra:
  recipe-maintainers:
    - ocefpaf
