{% set version = "3.1.3" %}

package:
    name: uncertainties
    version: {{ version }}

source:
  url: https://pypi.io/packages/source/u/uncertainties/uncertainties-{{ version }}.tar.gz
  sha256: 00243c782194f81d73db1e22887583a863de19417cfb71ff3dbe675ef169631d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy

test:
  imports:
    - uncertainties
    - uncertainties.unumpy
  requires:
    - numpy

about:
  home: https://pypi.python.org/pypi/uncertainties
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'Transparent calculations with uncertainties on the quantities involved (aka "error propagation"); fast calculation of derivatives.'

extra:
  recipe-maintainers:
    - ocefpaf
