{% set version = "3.0.1" %}

package:
    name: uncertainties
    version: {{ version }}

source:
    fn: uncertainties-{{ version }}.tar.gz
    url: https://github.com/lebigot/uncertainties/archive/{{ version }}.tar.gz
    sha256: eb7024831466a73bba7473e8378057a4eece3818c90225b7a64527ede5dbf1d4

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy

test:
    imports:
        - uncertainties
        - uncertainties.unumpy
    requires:
        - nose
        - numpy

about:
    home: http://pythonhosted.org/uncertainties/
    license: BSD 3-Clause
    summary: 'Transparent calculations with uncertainties on the quantities involved (aka "error propagation"); fast calculation of derivatives.'

extra:
    recipe-maintainers:
        - ocefpaf
