{% set version = "2.4.8.1" %}

package:
    name: uncertainties
    version: {{ version }}

source:
    fn: uncertainties-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/u/uncertainties/uncertainties-{{ version }}.tar.gz
    sha256: 188b73e16983302cbed7cb24352be8542a0cc9bb0ae162829cf181e446bf361c

build:
    number: 1
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy

test:
    imports:
        - uncertainties
        - uncertainties.unumpy
    requires:
        - nose
        - numpy

about:
    home: http://pythonhosted.org/uncertainties/
    license: BSD 3-Clause
    summary: 'Transparent calculations with uncertainties on the quantities involved (aka "error propagation"); fast calculation of derivatives.'

extra:
    recipe-maintainers:
        - ocefpaf
