{% set version = "3.1.5" %}

package:
  name: uncertainties
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/u/uncertainties/uncertainties-{{ version }}.tar.gz
  sha256: 9122c1e7e074196883b4a7a946e8482807b2f89675cb5e3798b87e0608ede903

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - future
    # optional
    - numpy

test:
  imports:
    - uncertainties
    - uncertainties.unumpy
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://pypi.python.org/pypi/uncertainties
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Transparent calculations with uncertainties on the quantities involved (aka "error propagation"); fast calculation of derivatives.

extra:
  recipe-maintainers:
    - ocefpaf
