travis:
  secure:
    BINSTAR_TOKEN: JIckp7aiApW5GN8BmRr8O+SUxYvgqvVe+XF0Sx/n+tHuYL+JOvftJUW5onbkX5aRwtkOrGBAVFmECDQTYWVwiCnUq/J5rdhce9xxG7ECiigOoP9TlhxSmyxUPJv4nV2w7NH0KpBkFDaJ7Hiei/2X18b91PxtW1dGYDXhcT+rgU11tmPzJRdWxyPC1TuiRPliKp0/4EBMqGHCOXjhN6m/+2jAH5Oh0Hfi6hB12QDNnIjK4ckLPZU2rDY5nC+UttE4wTlZa/CYvv8MrhduYiFun2r47rFT6nY2ZEd3RDaja+xARmRLkv4WVbNFPg1L6gFZp3u61YaguomC8lEYbQIDImh+fKzH65AITlOEw1sbHy8dU19LxbpoCIUOKh1iyMmwFszSRtQ6Z6HvnixLvpM05ra8iQ49PvAMOxALaF095jGNbhoYs/c7bTqbGlVrm2OWryw6dcugwt9dZBwwMoToV3+AAGb8vZ+6QzIZzvCBAXnU5ifYP0ScN7kOt/NgjETQI1jl6e7Ic8gf18lJn6OdPPg86CIzKakBOyWOA3w885JVIEx9RDID4g57t9+P6LOV9UNwPKMUTvUWdN/U34B7LNPTzqnq99OUKMhRykj+3FaGvQS4dJUU/TdZuxUcY7Kke6IlDUb7THksr1kcYA17ZFAEvi3ADDwRUL/WsolBv9k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
