travis:
  secure:
    BINSTAR_TOKEN: Ze6C+Q31GHh+ySv1SxAcupx02H16nGU6mqqNmNsyQhc20wA5bsMYCD4KAObQIR7WoGlocX6ApK/SljxU/zofrWMztoM2D8X7IRgo/KCSYE6z7aBjqxtlFT1dt6mII6JubkahANHTMyoiDuunfyYOSqz/dpFqWxNRO40gAP3LNlFr62Vnq7JdawZso0KJ5N45VlQTJFM7wXJvzYXtkIkCNYtq3G42GgPwm1IzV3cU1VbbPe03lY4Me4jZPNvawawqqF3deeowl7sjqvGL/SayX8fHB+9dh0FCS331mctTWUN8iDIkv6OyI94FLi0/91JNejlK+AjaKvmZ1BoecjuLq5UwAMCB9UBwELLkYZvMdL/yrb6+s0VvoklO5d4tjD+y1HJzUsNGMZ6ZKHrrs9/8KTjdDq4jaQbkSkYS52C9QOhYMs1tOhcl39pu0Gjh5zibFvybeLU5P+/I+GoM3lr5YVFGASMa4Ipa+iSUYsy3CCFr+3qMIIyKQLmaPkwqwo7xA3Y+TuiYDiym8v7aXmq3t4O1OrXnmWyQSeh8TlNE7JVvW2KghAuRYavKo5f6JJ9mP7xbfJDnyk1CifrrNO6MhaY7VJJ0luuCy2fGGTIt3x9m9pR2AkD1GF07D5iRrhvBrdVFypwmudvOaTi43MiMnNCi6o32K2ywF7ymUCbuWT8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
