travis:
  secure:
    BINSTAR_TOKEN: AcPgZMqdAWeel6plnPDi4oBNy4rpCD691r6M7pO/cOo9gd9gwdylbauwlenKbEyOeuWfKa52rOgcEpttV1Hl/z84lzXs/+m2vxW88yKlcGH2OO/W+y365h8plY/di4jZja96R7Qt14tQ4jwV02LLobob0Qxi6eYPEz5Z8iyzo5I8ByHYDIWJcbGBw+fHOjot+cPSLx8HL3wlEePcCLJoLhXY9W9xRXKqKElqKnU9CiPFBwrEMsHYpmBpzd+75yYc/H/vjlLdtQrLsbN7Dlw79kdEVDcyM7Lo7kbUPtUBgoIxtV/tCmnbCMB4WbeGKNicKQkjS/eDlDjv2rW9hKcaF/YFZYNWZb1Fa2QTO/+NuSHe3ltnTCYCOJ5gNkvH66aTxvz1UZvyJ1fQc2Nx88/kAo9McJdFYWY2O26UhvJWlLqIrJKPqyzFDRo+ibuVDt7SoRRZkaIM8UtEdT9Yc+FoFWkO42UAn68ktaxf1I9K0cnmTKJZ30VZ5UAz2J8CEi7OqF59hSurpfha/3wLDRoDXJkN8Qgt95IKVLcnlZFvmhJz0980PYnVVDruOK1dhFYconOaYcwe+rmpYCsaFTvNtONRHvte2HwZPdrH0fyL7xH27+FwE15zLZMufwxT+VnkgWFg/p0FY5TM3tL3vGkjHBMhj9UGzNKkRZTrVdDT7hY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
